config/routes.rb
Roomz::Application.routes.draw do
  resources :rooms

  root :to => "rooms#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/room.rb
# coding: utf-8
class Room < ActiveRecord::Base
  belongs_to :user
end

app/models/tweet.rb
# coding: utf-8
class Tweet
  attr_accessor :post

  #-----------------------#
  # self.set_search_param #
  #-----------------------#
  def self.set_search_param( args )
    search_param = ""
    search_param += "?q=#{CGI.escape( args[:q] + ' -RT' )}"
    search_param += "&locale=ja"
    search_param += "&lang=ja"
    search_param += "&rpp=#{args[:rpp]}"
    search_param += "&page=#{args[:page]}"
    search_param += "&show_user=false"
    search_param += "&result_type=recent"

    return search_param
  end

end

app/models/user.rb
# coding: utf-8
class User < TwitterAuth::GenericUser
  # Extend and define your user model as you see fit.
  # All of the authentication logic is handled by the 
  # parent TwitterAuth::GenericUser class.
  
  has_one :room

end

app/models/utility.rb
# coding: utf-8
class Utility
  def self.replace_message( message )
    message.to_s.gsub!( "You have logged in successfully.", "ログインが完了しました。")
    
    return message
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rooms_controller.rb
# coding: utf-8
class RoomsController < ApplicationController
  before_filter :login_authorize, :except => [ :index ]

  $per_page = 30

  #-------#
  # index #
  #-------#
  def index
    if session[:user_id].present? and session[:access_url].present?
      redirect_to session[:access_url]
      session[:access_url] = nil
      return
    end
    
    @rooms = Room.all( :include => :user )
  end

  #-----#
  # new #
  #-----#
  def new
    @room = Room.new( :hash_tag => "#")
    
    @submit = "create"
  end

  #------#
  # edit #
  #------#
  def edit
    @room = Room.where( :id => params[:id] ).first
    redirect_to :action => "index" and return if @room.blank?

    @submit = "update"
  end

  #--------#
  # create #
  #--------#
  def create
    @room = Room.new( params[:room] )
    @room.user_id = session[:user_id]

    if @room.save
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  #--------#
  # update #
  #--------#
  def update
    @room = Room.where( :id => params[:id] ).first
    redirect_to :action => "index" and return if @room.blank?

    if @room.update_attributes( params[:room] )
      redirect_to :action => "index"
    else
      flash[:notice] = "ルームの更新に失敗しました。"
      @submit = "update"
      render :action => "edit"
    end
  end

  #---------#
  # destroy #
  #---------#
  def destroy
    @room = Room.where( :id => params[:id] ).first
    redirect_to :action => "index" and return if @room.blank?

    @room.destroy

    redirect_to :action => "index"
  end

  #------#
  # show #
  #------#
  def show
    @room = Room.where( :id => params[:id] ).first( :include => "user" )
    redirect_to :action => "index" and return if @room.blank?
    
    params[:tweet_page] = 1 if params[:tweet_page].blank? or params[:tweet_page].to_i <= 0
    params[:tweet_page] = ( 1500 / $per_page ) if !params[:tweet_page].blank? and params[:tweet_page].to_i >= ( 1500 / $per_page )
    search_param = Tweet.set_search_param( :q => @room.hash_tag, :rpp => $per_page, :page => params[:tweet_page] )
    @twitter_get = current_user.twitter.get( "http://search.twitter.com/search.json#{search_param}" )
  end
  
  #------#
  # post #
  #------#
  def post
    @room = Room.where( :id => params[:id] ).first
    redirect_to :action => "index" and return if @room.blank?

    post_tweet = "#{params[:tweet][:post].presence} #{@room.hash_tag}"

    # Twitter投稿
    begin
      if current_user.twitter.post( '/statuses/update.json', :status => post_tweet )
        flash[:tweet_notice] = "<p style=\"color: green\">Twitterへの投稿が完了しました。</p>"
      else
        flash[:tweet_notice] = "<p style=\"color: red;\">Twitterへの投稿に失敗しました。</p>"
      end
    rescue => exc
      flash[:tweet_notice] = "<p style=\"color: red;\">#{exc}</p>"
    end
    
    redirect_to :action => "show", :id => params[:id] and return
  end
  
  #------------#
  # char_count #
  #------------#
  def char_count
    render :text => ( 140 - 1 - params[:value].length - params[:hash_tag_length].to_i )
  end

  private
  
  #-----------------#
  # login_authorize #
  #-----------------#
  def login_authorize
    if session[:user_id].blank?
      session[:access_url] = request.url
      flash[:notice] = "ログインして下さい。"
      redirect_to :action => "index" and return
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  unloadable

  def new
    if TwitterAuth.oauth?
      oauth_callback = request.protocol + request.host_with_port + '/oauth_callback'
      @request_token = TwitterAuth.consumer.get_request_token({:oauth_callback=>oauth_callback})
      session[:request_token] = @request_token.token
      session[:request_token_secret] = @request_token.secret
     
      url = @request_token.authorize_url
      url << "&oauth_callback=#{CGI.escape(TwitterAuth.oauth_callback)}" if TwitterAuth.oauth_callback?      
      redirect_to url
    else
      # we don't have to do anything, it's just a simple form for HTTP basic!
    end
  end

  def create
    logout_keeping_session!
    if user = User.authenticate(params[:login], params[:password])
      self.current_user = user
      authentication_succeeded and return
    else
      authentication_failed('Unable to verify your credentials through Twitter. Please try again.', '/login') and return
    end
  end

  def oauth_callback
    unless session[:request_token] && session[:request_token_secret] 
      authentication_failed('No authentication information was found in the session. Please try again.') and return
    end

   unless params[:oauth_token].blank? || session[:request_token] ==  params[:oauth_token]
     authentication_failed('Authentication information does not match session information. Please try again.') and return
   end

    @request_token = OAuth::RequestToken.new(TwitterAuth.consumer, session[:request_token], session[:request_token_secret])

    oauth_verifier = params["oauth_verifier"]
    @access_token = @request_token.get_access_token(:oauth_verifier => oauth_verifier)
    
    # The request token has been invalidated
    # so we nullify it in the session.
    session[:request_token] = nil
    session[:request_token_secret] = nil

    @user = User.identify_or_create_from_access_token(@access_token)

    session[:user_id] = @user.id

    cookies[:remember_token] = @user.remember_me

    authentication_succeeded 
  rescue Net::HTTPServerException => e
    case e.message
      when '401 "Unauthorized"'
        authentication_failed('This authentication request is no longer valid. Please try again.') and return
      else
        authentication_failed('There was a problem trying to authenticate you. Please try again.') and return
    end
  # OAuth Unauthorized Rescue Add
  rescue OAuth::Unauthorized => e
    authentication_failed(t('This authentication request is no longer valid Please try again')) and return
  end
  
  def destroy
    logout_keeping_session!
    redirect_back_or_default('/')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roomz</title>
  <%#= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'base' %>
  <%= stylesheet_link_tag 'base_override' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body>

<div class="page_box">

<%# ヘッダメニュー %>
<span class="header_menu menu">
  <%# ログイン判定 %>
  <% unless session[:user_id].blank? %>
    <%# ログイン後 %>
    <%= link_to t("menu.logout"), logout_path, :confirm => 'ログアウトしますか？' %>
  <% else %>
    <%# ログイン前 %>
    <%= link_to t("menu.login"), login_path %>
  <% end %>
</span>

<%# タイトル %>
<span id="title">
  <%= link_to t("menu.title"), :root %>
</span>

<br />
<br />

<%= yield %>

</div>

</body>

</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
<%# form_for :room, :url => { :action => "create" } do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label t("room.hash_tag") %><br />
    <%= f.text_field :hash_tag, :class => "input_field_width_300" %><br />
  </div>
  
  <br />
  <br />

  <div>
    <%= f.label t("room.site") %><br />
    <%= f.text_field :site, :class => "input_field_width_300" %><br />
  </div>

  <br />
  <br />

  <div>
    <%= f.submit t("menu.#{@submit}"), :disable_with => t("menu.#{@submit}") %>
    <br />
  </div>
<% end %>

app/views/rooms/_tweet_paging.html.erb

<%# ---------- Tweetページング ---------- %>
<div class="pagination">
  <% if !params[:tweet_page].blank? and !(params[:tweet_page].to_i == 1) %>
    <%= link_to t("menu.prev"), { :action => "show", :anchor => "tweet_top", :id => params[:id], :tweet_page => ( params[:tweet_page].to_i - 1 ) }, :class => "prev_page", :rel => "prev start" %>
  <% else %>
  <span class="disabled prev_page"><%= t("menu.prev") %></span>
  <% end %>

  <%# 最初4ページ %>
  <% 1.upto(4) { |count| %>
    <% if count == params[:tweet_page].to_i %>
      <%# カレントページ %>
      <%= link_to params[:tweet_page], { :action => "show", :anchor => "tweet_top", :reload => rand(100), :id => params[:id], :tweet_page => params[:tweet_page] }, :class => "current_link" %>
    <% else %>
      <%= link_to count, { :action => "show", :anchor => "tweet_top", :id => params[:id], :tweet_page => count } %>
    <% end %>
  <% } %>

  <%# ページ番号が7より大きければ %>
  <% if 7 < params[:tweet_page].to_i %>
    <span class="gap">...</span>
  <% end %>

  <%# ページ番号-2～ページ番号-1 %>
  <% (params[:tweet_page].to_i - 2).upto(params[:tweet_page].to_i - 1) { |count| %>
    <% if 4 < count and !( ( (1500 / $per_page) - 3 ) <= count ) %>
      <%= link_to count, { :action => "show", :anchor => "tweet_top", :id => params[:id], :tweet_page => count } %>
    <% end %>
  <% } %>

  <%# カレントページ %>
  <%# ページ番号が最初4ページ／最後4ページに含まれていなければ %>
  <% unless ( 1 <= params[:tweet_page].to_i and params[:tweet_page].to_i <= 4 ) or ( ( (1500 / $per_page) - 3 ) <= params[:tweet_page].to_i and params[:tweet_page].to_i <= ( 1500 / $per_page ) ) %>
    <%= link_to params[:tweet_page], { :action => "show", :anchor => "tweet_top", :reload => rand(100), :id => params[:id], :tweet_page => params[:tweet_page] }, :class => "current_link" %>
  <% end %>

  <%# ページ番号+1～ページ番号+2 %>
  <% (params[:tweet_page].to_i + 1).upto(params[:tweet_page].to_i + 2) { |count| %>
    <% if count < ( (1500 / $per_page) - 3 ) and !(count <= 4) %>
      <%= link_to count, { :action => "show", :anchor => "tweet_top", :id => params[:id], :tweet_page => count } %>
    <% end %>
  <% } %>

  <%# ページ番号がMAXページ-6より小さければ %>
  <% if params[:tweet_page].to_i < ( (1500 / $per_page) - 6 ) %>
    <span class="gap">...</span>
  <% end %>
  
  <%# 最後4ページ %>
  <% ( (1500 / $per_page) - 3 ).upto( 1500 / $per_page ) { |count| %>
    <% if count == params[:tweet_page].to_i %>
      <%# カレントページ %>
      <%= link_to params[:tweet_page], { :action => "show", :anchor => "tweet_top", :reload => rand(100), :id => params[:id], :tweet_page => params[:tweet_page] }, :class => "current_link" %>
    <% else %>
      <%= link_to count, { :action => "show", :anchor => "tweet_top", :id => params[:id], :tweet_page => count } %>
    <% end %>
  <% } %>

  <% unless params[:tweet_page].to_i == ( 1500 / $per_page ) %>
    <%= link_to t("menu.next"), { :action => "show", :anchor => "tweet_top", :id => params[:id], :tweet_page => ( params[:tweet_page].to_i + 1 ) }, :class => "next_page", :rel => "next" %>
  <% else %>
    <span class="disabled next_page"><%= t("menu.next") %></span>
  <% end %>
</div>
<%# ---------- ／ Tweetページング ---------- %>

app/views/rooms/edit.html.erb
<p id="notice"><%= notice %><% unless notice.blank? %><br /><br /><% end %></p>

<%= render 'form' %>

<br />
<br />

<span class="menu">
  <%= link_to t("menu.list"), rooms_path %>
</span>

<br />
<br />

app/views/rooms/index.html.erb
<p id="notice"><%= Utility.replace_message( flash[:notice] ) %></p>

<table>
  <tr>
    <th><%= t("room.hash_tag") %></th>
    <th><%= t("room.site") %></th>
    <th><%= t("room.user") %></th>
    <% unless session[:user_id].blank? %>
    <th></th>
    <th></th>
    <% end %>
  </tr>

<% @rooms.each do |room| %>
  <tr class="top_line">
    <td><%= link_to room.hash_tag, room %></td>
    <td><%= link_to room.site, room.site, :target => "_blank" %></td>
    <td align="center"><%= link_to image_tag( room.user.profile_image_url, :size => t("user.profile_size"), :alt => t("user.icon_alt"), :title => "#{room.user.login}／#{room.user.name}" ), "http://twitter.com/#!/#{room.user.login}", :target => "_blank" unless room.user.blank? %></td>
    <% if session[:user_id].present? and session[:user_id].to_s == room.user_id.to_s %>
      <td class="menu"><%= link_to t("menu.edit"), edit_room_path(room) %></td>
      <td class="menu"><%= link_to t("menu.destroy"), room, :confirm => '本当に削除してよろしいですか？', :method => :delete %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
  </tr>
<% end %>

  <tr class="top_line">
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

<% unless session[:user_id].blank? %>
<br />

<span class="menu">
  <%= link_to t("menu.new"), new_room_path %>
</span>
<% end %>

<br />
<br />

app/views/rooms/new.html.erb
<%= render 'form' %>

<br />
<br />

<span class="menu">
  <%= link_to t("menu.list"), rooms_path %>
</span>

<br />
<br />

app/views/rooms/show.html.erb
<%# ルーム情報 %>
<table>
  <tr class="info">
    <td style="white-space: nowrap;">
      <%# ハッシュタグ %>
      <%= t("room.hash_tag") %>：<%= @room.hash_tag %><br />
    </td>
  </tr>

  <tr class="info">
    <td style="white-space: nowrap;">
      <%# サイトURL %>
      <%= t("room.site") %>：<%= link_to @room.site, @room.site, :target => "_blank" unless @room.site.blank? %><br />
    </td>
  </tr>

  <tr class="info">
    <td style="white-space: nowrap;">
      <%# オーナー %>
      <%= t("room.user") %>：<%= link_to image_tag( @room.user.profile_image_url, :size => t("user.profile_size"), :alt => t("user.icon_alt"), :title => "#{@room.user.login}／#{@room.user.name}" ), "http://twitter.com/#!/#{@room.user.login}", :target => "_blank" unless @room.user.blank? %><br />
    </td>
  </tr>

  <tr class="info">
    <td style="white-space: nowrap;">
      <%# 検索 %>
      検索：<%= link_to "Twitter", "http://twitter.com/#!/search/#{CGI.escape(@room.hash_tag)}", :target => "_blank" %>　<%= link_to "Masher", "http://masher.heroku.com/#{@room.hash_tag.sub("#","")}", :target => "_blank" %>
      <%#= link_to "Google", "http://www.google.co.jp/search?q=#{CGI.escape(@room.hash_tag)}&hl=ja&biw=1131&bih=754&prmd=ivns&source=lnms&tbs=mbl:1&ei=WxWTTcqGIJHqvQPT-Zi9CA&sa=X&oi=mode_link&ct=mode&cd=9&ved=0CB4Q_AUoCA&prmdo=1#q=#{CGI.escape(@room.hash_tag)}+site%3Atwitter.com&tbs=mbl:1&tbo=1&hl=ja&lr=lang_ja&prmdo=1&tbm=mbl&sa=X&ei=gM7lTYzGI4mOvQPOk5CECw&ved=0CCMQsQcwAA&bav=on.2,or.r_gc.r_pw.&fp=a7fd3f5679dbb192&biw=1123&bih=716", :target => "_blank" %>
      <br />
    </td>
  </tr>
</table>

<br />

<%# メニュー %>
<span class="menu">
  <%#= link_to t("menu.list"), { :controller => "rooms" } %>
  <%= link_to t("menu.list"), { :action => "index" } %>
  <%= link_to t("menu.reload"), { :action => "show", :id => params[:id] } %>
</span><br />

<br />

<%# メッセージ %>
<% unless flash[:tweet_notice].blank? %>
  <%=raw flash[:tweet_notice] %>
  <br />
<% end %>

<%# Tweet投稿 %>
<%= form_for :tweet, :url => { :action => "post", :id => @room.id } do |f| %>
<table>
  <tr>
    <%# Tweet入力エリア %>
    <td style="white-space: nowrap;" colspan="4">
      <%= f.text_area :post, :size => "50x3" %>
    </td>
  </tr>

  <tr>
    <td align="right">
      <%# ハッシュタグ %>
      <%= @room.hash_tag unless @room.blank? %>
      
      <%# 入力文字数カウント %>
      <span id="char_count"><%= 140 - 1 - @room.hash_tag.length %></span>
      <%= observe_field(
        :tweet_post,
        :frequency => 0.25,
        :update => :char_count,
        :url => { :action => :char_count, :hash_tag_length => @room.hash_tag.length },
        :with => "value"
        )
      %>
      
      <%# Tweetボタン %>
      <%= f.submit t("tweet.post"), :disable_with => t("tweet.post") %>
    </td>
  </tr>
</table>
<% end %>

<br />

<%# アンカーターゲット %>
<span id="tweet_top"></span>

<%# Tweetページング %>
<%= render :partial => "tweet_paging" %>

<br />

<%# Tweet検索結果がブランクでなければ %>
<% unless @twitter_get["results"].blank? %>

<%# Tweet検索結果 %>
<table>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

<% @twitter_get["results"].each do |result| %>
  <tr class="top_line">
    <%# プロフィール画像 %>
    <td style="width: 15px;">
      <%= link_to image_tag( result["profile_image_url"], :size => t("user.profile_size"), :alt => t("user.icon_alt"), :title => result["from_user"] ), "http://twitter.com/#!/#{result["from_user"]}", :target => "_blank" %>
    </td>
    
    <%# ユーザ名 %>
    <td>
      <%= link_to result["from_user"], "http://twitter.com/#!/#{result["from_user"]}", :target => "_blank" %>
    </td>
    
    <%# Tweet %>
    <td><%= result["text"] %></td>

    <%# 投稿時刻 %>
    <td style="white-space: nowrap;">
      <%= link_to Time.parse( result["created_at"] ).strftime("%Y/%m/%d %H:%M"), "https://twitter.com/#!/masason/status/#{result["id_str"]}", :target => "_blank" unless result["created_at"].blank? %>
    </td>
  </tr>
<% end %>

  <tr class="top_line">
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

<%# Tweetページング %>
<%= render :partial => "tweet_paging" %>

<br />

<% end %>

<br />

<%# メニュー %>
<span class="menu">
  <%#= link_to t("menu.list"), { :controller => "rooms" } %>
  <%= link_to t("menu.list"), { :action => "index" } %>
  <%= link_to t("menu.reload"), { :action => "show", :id => params[:id] } %>
</span>

<br />
<br />